export const FONT_ASSETS = {
  "Galada-Regular": require("../assets/fonts/Galada-Regular.ttf"),
  "Mona-Sans-Regular": require("../assets/fonts/Mona-Sans-Regular.ttf"),
  "Mona-Sans-Medium": require("../assets/fonts/Mona-Sans-Medium.ttf"),
  "Mona-Sans-SemiBold": require("../assets/fonts/Mona-Sans-SemiBold.ttf"),
  "Mona-Sans-Bold": require("../assets/fonts/Mona-Sans-Bold.ttf"),
  "Pattaya-Regular": require("../assets/fonts/Pattaya-Regular.ttf"),
  "Molle-Italic": require("../assets/fonts/signature/Molle-Italic.ttf"),
  "MonsieurLaDoulaise-Regular": require("../assets/fonts/signature/MonsieurLaDoulaise-Regular.ttf"),
  "MonteCarlo-Regular": require("../assets/fonts/signature/MonteCarlo-Regular.ttf"),
  "Montez-Regular": require("../assets/fonts/signature/Montez-Regular.ttf"),
  Alysa: require("../assets/fonts/custom/Alysa.ttf"),
  Atziluth: require("../assets/fonts/custom/Atziluth.ttf"),
  Auttan: require("../assets/fonts/custom/auttan.ttf"),
  Bathoock: require("../assets/fonts/custom/bathoock.otf"),
  Claudia: require("../assets/fonts/custom/claudia.ttf"),
  DearScript: require("../assets/fonts/custom/dearscript.otf"),
  Firdaus: require("../assets/fonts/custom/Firdaus.ttf"),
  GitaScript: require("../assets/fonts/custom/GitaScript.ttf"),
  Harlfiney: require("../assets/fonts/custom/Harlfiney.ttf"),
  Marcelle: require("../assets/fonts/custom/Marcelle.ttf"),
  MessyScript: require("../assets/fonts/custom/MessyScript.ttf"),
  Scripty: require("../assets/fonts/custom/Scripty.ttf"),
  Shelly2: require("../assets/fonts/custom/shelly2.ttf"),
  WildScript: require("../assets/fonts/custom/wildscriptpl.ttf"),
  JUSTSansOutline: require("../assets/fonts/outline/JUSTSansOutlineExBold.otf"),
  OrangeAvenueOutline: require("../assets/fonts/outline/OrangeAvenueOutlineDEMORegular.otf"),
  Outline: require("../assets/fonts/outline/Outline.ttf"),
  OutlineMirage: require("../assets/fonts/outline/OutlineMirageLine.ttf"),
  OutlineStyle: require("../assets/fonts/outline/OutlineStyle.ttf"),
  OutlineTwelve: require("../assets/fonts/outline/OutlineTwelve.ttf"),
  RostexOutline: require("../assets/fonts/outline/RostexObliqueOutline.ttf"),
  RuritaniaOutline: require("../assets/fonts/outline/RuritaniaOutline.ttf"),
  SFDistantOutline: require("../assets/fonts/outline/SFDistantGalaxyOutlineItalic.ttf"),
  Academy: require("../assets/fonts/outline/academyregular.ttf"),
  Gunplay3D: require("../assets/fonts/outline/gunplay3dregular.otf"),
  KlarissaShadow: require("../assets/fonts/outline/klarissashadow.ttf"),
  NoctraOutline: require("../assets/fonts/outline/noctradripoutlinemeltoutlinemelt.ttf"),
  OutlineBubble: require("../assets/fonts/outline/outlinebubbleregular.ttf"),
  ProRacingOutline: require("../assets/fonts/outline/proracingoutline.otf"),
  SpookyCreepy: require("../assets/fonts/outline/spookycreepyregular.ttf"),
  UniversidadOutline: require("../assets/fonts/outline/universidadpersonalusebold.ttf"),
} as const;

export const FontFamily = {
  regular: "Mona-Sans-Regular",
  medium: "Mona-Sans-Medium",
  semibold: "Mona-Sans-SemiBold",
  bold: "Mona-Sans-Bold",
  galada: "Galada-Regular",
  pattaya: "Pattaya-Regular",
  signatureMolle: "Molle-Italic",
  signatureMonsieurLaDoulaise: "MonsieurLaDoulaise-Regular",
  signatureMonteCarlo: "MonteCarlo-Regular",
  signatureMontez: "Montez-Regular",
  customAlysa: "Alysa",
  customAtziluth: "Atziluth",
  customAuttan: "Auttan",
  customBathoock: "Bathoock",
  customClaudia: "Claudia",
  customDearScript: "DearScript",
  customFirdaus: "Firdaus",
  customGitaScript: "GitaScript",
  customHarlfiney: "Harlfiney",
  customMarcelle: "Marcelle",
  customMessyScript: "MessyScript",
  customScripty: "Scripty",
  customShelly2: "Shelly2",
  customWildScript: "WildScript",
  outlineJustSans: "JUSTSansOutline",
  outlineOrangeAvenue: "OrangeAvenueOutline",
  outlineRegular: "Outline",
  outlineMirage: "OutlineMirage",
  outlineStyle: "OutlineStyle",
  outlineTwelve: "OutlineTwelve",
  outlineRostex: "RostexOutline",
  outlineRuritania: "RuritaniaOutline",
  outlineSFDistant: "SFDistantOutline",
  outlineAcademy: "Academy",
  outlineGunplay: "Gunplay3D",
  outlineKlarissa: "KlarissaShadow",
  outlineNoctra: "NoctraOutline",
  outlineBubble: "OutlineBubble",
  outlineProRacing: "ProRacingOutline",
  outlineSpooky: "SpookyCreepy",
  outlineUniversidad: "UniversidadOutline",
} as const;

// Typography helper functions
export const typography = {
  h1: { fontFamily: FontFamily.bold, fontSize: 28, lineHeight: 34 },
  h2: { fontFamily: FontFamily.bold, fontSize: 24, lineHeight: 30 },
  h3: { fontFamily: FontFamily.semibold, fontSize: 20, lineHeight: 26 },
  h4: { fontFamily: FontFamily.semibold, fontSize: 18, lineHeight: 24 },
  h5: { fontFamily: FontFamily.medium, fontSize: 16, lineHeight: 22 },
  h6: { fontFamily: FontFamily.medium, fontSize: 14, lineHeight: 20 },

  body: { fontFamily: FontFamily.regular, fontSize: 16, lineHeight: 24 },
  bodySmall: { fontFamily: FontFamily.regular, fontSize: 14, lineHeight: 20 },
  caption: { fontFamily: FontFamily.regular, fontSize: 12, lineHeight: 18 },

  button: { fontFamily: FontFamily.semibold, fontSize: 16, lineHeight: 20 },
  buttonSmall: { fontFamily: FontFamily.medium, fontSize: 14, lineHeight: 18 },

  label: { fontFamily: FontFamily.medium, fontSize: 12, lineHeight: 16 },

  galada: { fontFamily: FontFamily.galada, fontSize: 16, lineHeight: 24 },
} as const;
